### ISSUE TITLE
Fix tests with shoulda-matchers >= 4

### ISSUE THREAD

**Issue by ZeroPointEnergy** [sodabrew/puppet-dashboard#390]
two tests for model node_group_edge are failing with newer versions of shoulda-matchers because the gem now runs the validator and that causes an error.

```
Failures:

  1) NodeGroupEdge should belong to to required: 
     Failure/Error: "Creating a dependency from group '#{from.name}' to " \
     
     NoMethodError:
       undefined method `name' for nil:NilClass
     # ./app/models/node_group_edge.rb:17:in `dfs'
     # ./app/models/node_group_edge.rb:26:in `validate_dag'
     # ./spec/models/node_group_edge_spec.rb:4:in `block (2 levels) in <top (required)>'

  2) NodeGroupEdge should belong to from required: 
     Failure/Error: "Creating a dependency from group '#{from.name}' to " \
     
     NoMethodError:
       undefined method `name' for nil:NilClass
     # ./app/models/node_group_edge.rb:17:in `dfs'
     # ./app/models/node_group_edge.rb:26:in `validate_dag'
     # ./spec/models/node_group_edge_spec.rb:5:in `block (2 levels) in <top (required)>'
```
